# Generated by Django 5.0.3 on 2024-08-22 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0004_kniha_vydavatelstvi_alter_kniha_pocet_stran_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='tady napis recenzi', verbose_name='Text recenze')),
                ('kniha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='knihovna.kniha', verbose_name='Kniha')),
                ('recenzent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recenzent')),
            ],
        ),
    ]
